Rename HackMD and CodiMD to HedgeDoc
hedgedoc/container pull request #119
Opened 2020-11-08 20:29 UTC by hugopeixoto

To prepare for the rename, I replaced every occurrence of codimd with
hedgedoc.

There were still some stray hackmd references, so I replaced them as
well.

I removed the kubernetes instructions, since they were referring to
a helm chart that does not exist anymore.

There are two references to hackmd left. The first one is in the
migration guide from hackmd-docker to hedgedoc-container. The other one
is in a migration guide that points to
https://github.com/hackmdio/migration-to-0.5.0. Since this repository
wasn't forked (and there's no license attached), I left the reference as
is.

2020-11-08 20:54 UTC, ccoenen commented
0.5 has been around for a looooong time. Maybe we should cut ties and no longer mention that specific migration guide.

2020-11-08 21:05 UTC, hugopeixoto commented
Makes sense, I'll remove it.

2020-11-09 17:03 UTC, hugopeixoto commented on resources/docker-entrypoint.sh
> +    CMD_DB_URL="postgres://hedgedoc:hedgedocpass@hedgedocPostgres:5432/hedgedoc"
Does this mean we can remove `CMD_DB_URL` from docker-compose.yml, since they are both specifying the same URL?

2020-11-09 17:40 UTC, SISheogorath commented on resources/docker-entrypoint.sh
> +    CMD_DB_URL="postgres://hedgedoc:hedgedocpass@hedgedocPostgres:5432/hedgedoc"
In the docker-compose.yml it's used as an example to point out how it works and it's something one should change.

Here it's a fallback/default because we definitely don't want to use SQLite.

2020-11-09 20:38 UTC, davidmehren commented
Just for the record: Merging this is blocked by us moving to the `hedgedoc` org.

2020-11-09 21:43 UTC, hugopeixoto commented on resources/docker-entrypoint.sh
> +    CMD_DB_URL="postgres://hedgedoc:hedgedocpass@hedgedocPostgres:5432/hedgedoc"
Got it :+1: I've applied every change you suggested.

2020-11-17 13:36 UTC, mrdrogdrog commented
> Just for the record: Merging this is blocked by us moving to the `hedgedoc` org.

Project has been moved.

2020-11-17 17:05 UTC, Chasethechicken commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
Any particular reason why you didn't rename these ARGs to HEDGEDOC_REPOSITORY?

2020-11-17 17:12 UTC, mrdrogdrog commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
I guess it would be a breaking change?.. but you only need this during build time, right? 🤔

2020-11-17 17:13 UTC, SISheogorath commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
That's only for build time, yes, so feel free to change :)

2020-11-17 17:17 UTC, Chasethechicken commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
What would renaming this variable break? :thinking: 
It is only used while building the Dockerfile to specify which repository to pull from.
In theory the resulting container should not be any different if this variable was renamed...

2020-11-17 17:28 UTC, mrdrogdrog commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
Well. You could overwrite it with --build-arg. But that should be rather unusual, so change it please 😁

2020-11-17 17:29 UTC, SISheogorath commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
Good point. We could preserve backwards compatibility for the next few version by defining both.

2020-11-17 21:55 UTC, hugopeixoto commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
To answer the original question, I missed it when grepping for some reason, I was probably using case sensitive search.

Anyone using the images directly from quay won't be affected, so don't expect this to be widely used. Having a breaking change in this scenario, as long as it's not silent, doesn't seem harmful.

Unfortunately --build-args doesn't warn if the ARG is not declared, so changing it would make builds that are overriding it stop respecting the override and default to `hedgedoc/hedgedoc`.

What about this: instead of allowing both, we could error out if you're still using the old one, preventing the accidental use of the default value and forcing people to use the new variable.

What do you think?

2020-11-17 21:57 UTC, DerMolly commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
This sounds like a good solution to me

2020-11-17 22:27 UTC, hugopeixoto commented on alpine/Dockerfile
> +ARG CODIMD_REPOSITORY=https://github.com/hedgedoc/server.git
I added a commit with the behavior I suggested.

2020-11-17 22:38 UTC, mrdrogdrog requested changes

2020-11-17 22:38 UTC, mrdrogdrog commented on .travis.yml
We can't use travis anymore. Therefore any change to this file is redundant. There is another branch `feature/github-workflows` which handles the switch to github actions. We can wait for this branch to be merged or we include the changes into this one.

/cc @SISheogorath

2020-11-17 22:38 UTC, mrdrogdrog commented on README.md
> +[![#hedgedoc on matrix.org](https://img.shields.io/badge/Matrix.org-%23hedgedoc@matrix.org-green.svg)](https://app.element.io/#/room/#hedgedoc:matrix.org)
Please use `chat.hedgedoc.org` as link

2020-11-17 22:38 UTC, mrdrogdrog commented on README.md
> +[![Docker Repository on Quay](https://quay.io/repository/hedgedoc/server/status "Docker Repository on Quay")](https://quay.io/repository/hedgedoc/server)
The github repo was renamed from `server` to `hedgedoc`. Therefore the image maybe should also be named HedgeDoc?

2020-11-17 22:38 UTC, mrdrogdrog commented on README.md
> +[![Docker Repository on Quay](https://quay.io/repository/hedgedoc/server/status "Docker Repository on Quay")](https://quay.io/repository/hedgedoc/server)
(I'm not going to add this comment on every occurrence of `server`)

2020-11-17 22:38 UTC, mrdrogdrog commented on alpine/Dockerfile
>  # Disable PDF export on alpine
Pdf export isn't available in general in HedgeDoc

2020-11-18 00:02 UTC, hugopeixoto commented on README.md
> +[![Docker Repository on Quay](https://quay.io/repository/hedgedoc/server/status "Docker Repository on Quay")](https://quay.io/repository/hedgedoc/server)
yeah, I started this before I was aware that it was also being renamed :disappointed: I'll change it again.

2020-11-18 00:04 UTC, hugopeixoto commented on alpine/Dockerfile
>  # Disable PDF export on alpine
I would rather not pile on unrelated changes in this PR. I think this repo needs some love but it doesn't have to be all in one go.

2020-11-18 00:07 UTC, hugopeixoto commented on README.md
> +[![Docker Repository on Quay](https://quay.io/repository/hedgedoc/server/status "Docker Repository on Quay")](https://quay.io/repository/hedgedoc/server)
Done

2020-11-18 00:20 UTC, hugopeixoto commented on .travis.yml
I'm OK with waiting for CI to be reconfigured before merging this. I'll see if I can help there.

2020-11-20 16:42 UTC, mrdrogdrog requested changes

2020-11-20 16:42 UTC, mrdrogdrog commented on .github/workflows/test.yml
> +name: CI
Why did you change the name? This workflow runs tests, so it's more descriptive to name it that way.

2020-11-20 17:09 UTC, hugopeixoto commented on .github/workflows/test.yml
> +name: CI
"Run tests | passed" looked a bit weird in the README badge, I wasn't aware that that name would show up there when I wrote it, so I tried to change it to something that would be more adequate. Maybe just `tests`?

2020-11-20 17:36 UTC, mrdrogdrog commented on .github/workflows/test.yml
> +name: CI
`Tests` would be okay.

2020-11-20 17:55 UTC, mrdrogdrog requested changes

2020-11-20 17:55 UTC, mrdrogdrog commented on README.md
> +![CI status](https://github.com/hedgedoc/container/workflows/CI/badge.svg)
The link and the badge name is wrong.

2020-11-20 18:02 UTC, mrdrogdrog approved these changes

2020-11-20 18:31 UTC, davidmehren approved these changes

2020-11-20 19:12 UTC, merged